const countries = {
    Afghanistan: 'Afganistan',
    Aland_Islands: 'Islas Aland',
    Albania: 'Albania',
    Algeria: 'Argelia',
    American_Samoa: 'Samoa Americana',
    Andorra: 'Andorra',
    Angola: 'Angola',
    Anguilla: 'Anguila',
    Antigua_and_Barbuda: 'Antigua y Barbuda',
    Argentina: 'Argentina',
    Armenia: 'Armenia',
    Aruba: 'Aruba',
    Australia: 'Australia',
    Austria: 'Austria',
    Azerbaijan: 'Azerbaiyan',
    Azores: 'Azores',
    Bahamas: 'Bahamas',
    Bahrain: 'Bahrein',
    Balearic_Islands: 'Islas Baleares',
    Bangladesh: 'Bangladesh',
    Barbados: 'Barbados',
    Belarus: 'Bielorrusia',
    Belgium: 'Belgica',
    Belize: 'Belice',
    Benin: 'Benin',
    Bermuda: 'Islas Bermudas',
    Bhutan: 'Butan',
    Bolivia: 'Bolivia',
    Bonaire: 'Bonaire',
    Bosnia_and_Herzegovina: 'Bosnia y Herzegovina',
    Botswana: 'Botswana',
    Bouvet_Island: 'Isla Bouvet',
    Brazil: 'Brasil',
    Brunei: 'Brunei',
    Bulgaria: 'Bulgaria',
    Burkina_Faso: 'Burkina Faso',
    Burundi: 'Burundi',
    Cambodia: 'Camboya',
    Cameroon: 'Camerun',
    Canada: 'Canada',
    Canary_Islands: 'Islas Canarias',
    Cape_Verde: 'Cabo Verde',
    Cayman_Islands: 'Islas Caiman',
    Central_African_Republic: 'Republica Centroafricana',
    Chad: 'Chad',
    Chile: 'Chile',
    China: 'China',
    Christmas_Island: 'Isla de Navidad',
    Cocos_Islands: 'Islas Cocos',
    Colombia: 'Colombia',
    Comoros: 'Comoros',
    Congo_Brazzaville: 'Congo-Brazzaville',
    Congo_Kinshasa: 'Congo-Kinshasa',
    Cook_Islands: 'Islas Cook',
    Costa_Rica: 'Costa Rica',
    Croatia: 'Croacia',
    Cuba: 'Cuba',
    Curacao: 'Curacao',
    Cyprus: 'Chipre',
    Czech: 'Checo',
    Denmark: 'Dinamarca',
    Djibouti: 'Djibouti',
    Dominica: 'Dominica',
    Dominican_Republic: 'Republica Dominicana',
    Ecuador: 'Ecuador',
    Egypt: 'Egipto',
    El_Salvador: 'El Salvador',
    Equatorial_Guinea: 'Guinea Ecuatorial',
    Eritrea: 'Eritrea',
    Estonia: 'Estonia',
    Ethiopia: 'Etiopia',
    Falkland_Islands: 'Islas Malvinas',
    Faroe_Islands: 'Islas Faroe',
    Fiji: 'Fiji',
    Finland: 'Finlandia',
    France: 'Francia',
    French_Guiana: 'Guayana Francesa',
    French_Polynesia: 'Polinesia frances',
    French_Southern_Territories: 'Territorios Franceses del Sur',
    Gabon: 'Gabon',
    Gambia: 'Gambia',
    Georgia: 'Georgia',
    Germany: 'Alemania',
    Ghana: 'Ghana',
    Gibraltar: 'Gibraltar',
    Greece: 'Grecia',
    Greenland: 'Groenlandia',
    Grenada: 'Granada',
    Guadaloupe: 'Guadalupe',
    Guam: 'Guam',
    Guatemala: 'Guatemala',
    Guernsey: 'Guernsey',
    Guinea: 'Guinea',
    Guinea_Bissau: 'Guinea-Bissau',
    Guyana: 'Guayana',
    Haiti: 'Haiti',
    Heard_Island_and_McDonald_Islands: 'Escuchado Island y Islas McDonald',
    Honduras: 'Honduras',
    Hong_Kong: 'Hong Kong',
    Hungary: 'Hungria',
    Iceland: 'Islandia',
    India: 'India',
    Indonesia: 'Indonesia',
    Iran: 'Iran',
    Iraq: 'Irak',
    Ireland: 'Irlanda',
    Isle_of_Man: 'Isla del hombre',
    Israel: 'Israel',
    Italy: 'Italia',
    Ivory_Coast: 'Costa de Marfil',
    Jamaica: 'Jamaica',
    Japan: 'Japon',
    Jersey: 'Jersey',
    Jordan: 'Jordan',
    Kazakhstan: 'Kazajstan',
    Kenya: 'Kenia',
    Kiribati: 'Kiribati',
    Kosovo: 'Kosovo',
    Kuwait: 'Kuwait',
    Kyrgyzstan: 'Kirguistan',
    Laos: 'Laos',
    Latvia: 'Letonia',
    Lebanon: 'Libano',
    Lesotho: 'Lesoto',
    Liberia: 'Liberia',
    Libya: 'Libia',
    Liechtenstein: 'Liechtenstein',
    Lithuania: 'Lituania',
    Luxembourg: 'Luxemburgo',
    Macao: 'Macao',
    Macedonia: 'Macedonia',
    Madagascar: 'Madagascar',
    Madeira: 'Madeira',
    Malawi: 'Malawi',
    Malaysia: 'Malasia',
    Maldives: 'Maldivas',
    Mali: 'Mali',
    Malta: 'Malta',
    Marshall_Islands: 'Islas Marshall',
    Martinique: 'Martinica',
    Mauritania: 'Mauritania',
    Mauritius: 'Mauricio',
    Mayotte: 'Mayotte',
    Mexico: 'Mexico',
    Micronesia: 'Micronesia',
    Moldava: 'Moldava',
    Monaco: 'Monaco',
    Mongolia: 'Mongolia',
    Montenegro: 'Montenegro',
    Montserrat: 'Montserrat',
    Morocco: 'Marruecos',
    Mozambique: 'Mozambique',
    Myanmar: 'Myanmar',
    Nagorno_Karabakh: 'Nagorno-Karabakh',
    Namibia: 'Namibia',
    Nauru: 'Nauru',
    Nepal: 'Nepal',
    Netherlands: 'Paises Bajos',
    New_Caledonia: 'Nueva Caledonia',
    New_Zealand: 'Nueva Zelanda',
    Nicaragua: 'Nicaragua',
    Niger: 'Niger',
    Nigeria: 'Nigeria',
    Niue: 'Niue',
    Norfolk_Island: 'Isla Norfolk',
    North_Korea: 'Corea del Norte',
    Northern_Cyprus: 'El norte de Chipre',
    Northern_Mariana_Islands: 'Islas Marianas del Norte',
    Norway: 'Noruega',
    Oman: 'Oman',
    Pakistan: 'Pakistan',
    Palau: 'Palau',
    Palestine: 'Palestina',
    Panama: 'Panama',
    Papua_New_Guinea: 'Papua Nueva Guinea',
    Paraguay: 'Paraguay',
    Peru: 'Peru',
    Philippines: 'Filipinas',
    Pitcairn: 'Pitcairn',
    Poland: 'Polonia',
    Portugal: 'Portugal',
    Puerto_Rico: 'Puerto Rico',
    Qatar: 'Katar',
    Reunion: 'Reunion',
    Romania: 'Rumania',
    Russia: 'Rusia',
    Rwanda: 'Ruanda',
    Saba: 'Saba',
    Saint_Barthelemy: 'San Barthelemy',
    Saint_Eustatius: 'Santo Eustatius',
    Saint_Helena: 'Santa Helena',
    Saint_Kitts_and_Nevis: 'Saint Kitts y Nevis',
    Saint_Lucia: 'Santa Lucia',
    Saint_Martin_Dutch: 'Saint Martin-Dutch',
    Saint_Martin_French: 'Santo Martin-French',
    Saint_Pierre_and_Miquelon: 'Saint Pierre y Miquelon',
    Saint_Vincent_and_the_Grenadines: 'San Vicente y las Granadinas',
    Samoa: 'Samoa',
    San_Marino: 'San Marino',
    Sao_Tome_and_Principe: 'Santo Tome y Principe',
    Saudi_Arabia: 'Arabia Saudita',
    Senegal: 'Senegal',
    Serbia: 'Serbia',
    Seychelles: 'Seychelles',
    Sierra_Leone: 'Sierra Leona',
    Singapore: 'Singapur',
    Slovakia: 'Eslovaquia',
    Slovenia: 'Eslovenia',
    Solomon_Islands: 'Islas Salomon',
    Somalia: 'Somalia',
    Somaliland: 'Somalilandia',
    South_Africa: 'Sudafrica',
    South_Georgia_and_the_South_Sandwich_Islands: 'Georgia del sur y las islas Sandwich del sur',
    South_Korea: 'Corea',
    South_Sudan: 'Sudan del Sur',
    Spain: 'España',
    Sri_Lanka: 'Sri Lanka',
    Sudan: 'Sudan',
    Suriname: 'Surinam',
    Svalbard_and_Jan_Mayen: 'Svalbard y Jan Mayen',
    Swaziland: 'Swazilandia',
    Sweden: 'Suecia',
    Switzerland: 'Suiza',
    Syria: 'Siria',
    Tahiti: 'Tahiti',
    Taiwan: 'Taiwan',
    Tajikistan: 'Tayikistan',
    Tanzania: 'Tanzania',
    Thailand: 'Tailandia',
    Timor_Leste: 'Timor-Leste',
    Togo: 'Togo',
    Tokelau: 'Tokelau',
    Tonga: 'Tonga',
    Trinidad_and_Tobago: 'Trinidad y Tobago',
    Tunisia: 'Tunez',
    Turkey: 'Pavo',
    Turkmenistan: 'Turkmenistan',
    Turks_and_Caicos_Islands: 'Islas Turcas y Caicos',
    Tuvalu: 'Tuvalu',
    Uganda: 'Uganda',
    Ukraine: 'Ucrania',
    United_Arab_Emirates: 'Emiratos arabes Unidos',
    United_Kingdom: 'Reino Unido',
    United_States: 'Estados Unidos',
    Uruguay: 'Uruguay',
    Uzbekistan: 'Uzbekistan',
    Vanuatu: 'Vanuatu',
    Vatican_City: 'Ciudad del Vaticano',
    Venezuela: 'Venezuela',
    Vietnam: 'Vietnam',
    Virgin_Islands_British: 'Islas Virgenes-British',
    Virgin_Islands_US: 'Islas Virgenes-US',
    Wallis_and_Futuna: 'Wallis y Futuna',
    Yemen: 'Yemen',
    Zambia: 'Zambia',
    Zimbabwe: 'Zimbabue',
    America: 'America',
    Burma: 'Birmania',
    DRC: 'DRC',
    East_Timor: 'Timor este',
    England: 'Inglaterra',
    Holland: 'Holanda',
    Holy_city: 'Ciudad santa',
    Persia: 'Persia',
    Sint_Maarten: 'Sint Maarten',
}

const countries_api2 = {
    Afghanistan: 'Afganistan',
    Aland: 'Islas Aland',
    Albania: 'Albania',
    Algeria: 'Argelia',
    American: 'Samoa Americana',
    Andorra: 'Andorra',
    Angola: 'Angola',
    Anguilla: 'Anguila',
    Antigua: 'Antigua y Barbuda',
    Argentina: 'Argentina',
    Armenia: 'Armenia',
    Aruba: 'Aruba',
    Australia: 'Australia',
    Austria: 'Austria',
    Azerbaijan: 'Azerbaiyan',
    Azores: 'Azores',
    Bahamas: 'Bahamas',
    Bahrain: 'Bahrein',
    Balearic: 'Islas Baleares',
    Bangladesh: 'Bangladesh',
    Barbados: 'Barbados',
    Belarus: 'Bielorrusia',
    Belgium: 'Belgica',
    Belize: 'Belice',
    Benin: 'Benin',
    Bermuda: 'Islas Bermudas',
    Bhutan: 'Butan',
    Bolivia: 'Bolivia',
    Bonaire: 'Bonaire',
    Bosnia: 'Bosnia y Herzegovina',
    Botswana: 'Botswana',
    Bouvet: 'Isla Bouvet',
    Brazil: 'Brasil',
    Brunei: 'Brunei',
    Bulgaria: 'Bulgaria',
    Burkina: 'Burkina Faso',
    Burundi: 'Burundi',
    Cambodia: 'Camboya',
    Cameroon: 'Camerun',
    Canada: 'Canada',
    Canary: 'Islas Canarias',
    Cape: 'Cabo Verde',
    Cayman: 'Islas Caiman',
    Central: 'Republica Centroafricana',
    Chad: 'Chad',
    Chile: 'Chile',
    China: 'China',
    Christmas: 'Isla de Navidad',
    Cocos: 'Islas Cocos',
    Colombia: 'Colombia',
    Comoros: 'Comoros',
    Congo: 'Congo-Brazzaville',
    Congo: 'Congo-Kinshasa',
    Cook: 'Islas Cook',
    Costa: 'Costa Rica',
    Croatia: 'Croacia',
    Cuba: 'Cuba',
    Curacao: 'Curacao',
    Cyprus: 'Chipre',
    Czech: 'Checo',
    Denmark: 'Dinamarca',
    Djibouti: 'Djibouti',
    Dominica: 'Dominica',
    Dominican: 'Republica Dominicana',
    Ecuador: 'Ecuador',
    Egypt: 'Egipto',
    Salvador: 'El Salvador',
    Equatorial: 'Guinea Ecuatorial',
    Eritrea: 'Eritrea',
    Estonia: 'Estonia',
    Ethiopia: 'Etiopia',
    Falkland: 'Islas Malvinas',
    Faroe: 'Islas Faroe',
    Fiji: 'Fiji',
    Finland: 'Finlandia',
    France: 'Francia',
    French: 'Guayana Francesa',
    French: 'Polinesia frances',
    French: 'Territorios Franceses del Sur',
    Gabon: 'Gabon',
    Gambia: 'Gambia',
    Georgia: 'Georgia',
    Germany: 'Alemania',
    Ghana: 'Ghana',
    Gibraltar: 'Gibraltar',
    Greece: 'Grecia',
    Greenland: 'Groenlandia',
    Grenada: 'Granada',
    Guadaloupe: 'Guadalupe',
    Guam: 'Guam',
    Guatemala: 'Guatemala',
    Guernsey: 'Guernsey',
    Guinea: 'Guinea',
    Guinea: 'Guinea-Bissau',
    Guyana: 'Guayana',
    Haiti: 'Haiti',
    Heard: 'Escuchado Island y Islas McDonald',
    Honduras: 'Honduras',
    Hong: 'Hong Kong',
    Hungary: 'Hungria',
    Iceland: 'Islandia',
    India: 'India',
    Indonesia: 'Indonesia',
    Iran: 'Iran',
    Iraq: 'Irak',
    Ireland: 'Irlanda',
    Isle: 'Isla del hombre',
    Israel: 'Israel',
    Italy: 'Italia',
    Ivory: 'Costa de Marfil',
    Jamaica: 'Jamaica',
    Japan: 'Japon',
    Jersey: 'Jersey',
    Jordan: 'Jordan',
    Kazakhstan: 'Kazajstan',
    Kenya: 'Kenia',
    Kiribati: 'Kiribati',
    Kosovo: 'Kosovo',
    Kuwait: 'Kuwait',
    Kyrgyzstan: 'Kirguistan',
    Laos: 'Laos',
    Latvia: 'Letonia',
    Lebanon: 'Libano',
    Lesotho: 'Lesoto',
    Liberia: 'Liberia',
    Libya: 'Libia',
    Liechtenstein: 'Liechtenstein',
    Lithuania: 'Lituania',
    Luxembourg: 'Luxemburgo',
    Macao: 'Macao',
    Macedonia: 'Macedonia',
    Madagascar: 'Madagascar',
    Madeira: 'Madeira',
    Malawi: 'Malawi',
    Malaysia: 'Malasia',
    Maldives: 'Maldivas',
    Mali: 'Mali',
    Malta: 'Malta',
    Marshall: 'Islas Marshall',
    Martinique: 'Martinica',
    Mauritania: 'Mauritania',
    Mauritius: 'Mauricio',
    Mayotte: 'Mayotte',
    Mexico: 'Mexico',
    Micronesia: 'Micronesia',
    Moldava: 'Moldava',
    Monaco: 'Monaco',
    Mongolia: 'Mongolia',
    Montenegro: 'Montenegro',
    Montserrat: 'Montserrat',
    Morocco: 'Marruecos',
    Mozambique: 'Mozambique',
    Myanmar: 'Myanmar',
    Nagorno: 'Nagorno-Karabakh',
    Namibia: 'Namibia',
    Nauru: 'Nauru',
    Nepal: 'Nepal',
    Netherlands: 'Paises Bajos',
    New: 'Nueva Caledonia',
    New: 'Nueva Zelanda',
    Nicaragua: 'Nicaragua',
    Niger: 'Niger',
    Nigeria: 'Nigeria',
    Niue: 'Niue',
    Norfolk: 'Isla Norfolk',
    North: 'Corea del Norte',
    Northern: 'El norte de Chipre',
    Northern: 'Islas Marianas del Norte',
    Norway: 'Noruega',
    Oman: 'Oman',
    Pakistan: 'Pakistan',
    Palau: 'Palau',
    Palestine: 'Palestina',
    Panama: 'Panama',
    Papua: 'Papua Nueva Guinea',
    Paraguay: 'Paraguay',
    Peru: 'Peru',
    Philippines: 'Filipinas',
    Pitcairn: 'Pitcairn',
    Poland: 'Polonia',
    Portugal: 'Portugal',
    Puerto: 'Puerto Rico',
    Qatar: 'Katar',
    Reunion: 'Reunion',
    Romania: 'Rumania',
    Russia: 'Rusia',
    Rwanda: 'Ruanda',
    Saba: 'Saba',
    Saint: 'San Barthelemy',
    Saint: 'Santo Eustatius',
    Saint: 'Santa Helena',
    Saint: 'Saint Kitts y Nevis',
    Saint: 'Santa Lucia',
    Saint: 'Saint Martin-Dutch',
    Saint: 'Santo Martin-French',
    Saint: 'Saint Pierre y Miquelon',
    Saint: 'San Vicente y las Granadinas',
    Samoa: 'Samoa',
    San: 'San Marino',
    Sao: 'Santo Tome y Principe',
    Saudi: 'Arabia Saudita',
    Senegal: 'Senegal',
    Serbia: 'Serbia',
    Seychelles: 'Seychelles',
    Sierra: 'Sierra Leona',
    Singapore: 'Singapur',
    Slovakia: 'Eslovaquia',
    Slovenia: 'Eslovenia',
    Solomon: 'Islas Salomon',
    Somalia: 'Somalia',
    Somaliland: 'Somalilandia',
    Africa: 'Sudafrica',
    Georgia: 'Georgia del sur y las islas Sandwich del sur',
    Korea: 'Corea',
    Sudan: 'Sudan del Sur',
    Spain: 'España',
    Sri: 'Sri Lanka',
    Sudan: 'Sudan',
    Suriname: 'Surinam',
    Svalbard: 'Svalbard y Jan Mayen',
    Swaziland: 'Swazilandia',
    Sweden: 'Suecia',
    Switzerland: 'Suiza',
    Syria: 'Siria',
    Tahiti: 'Tahiti',
    Taiwan: 'Taiwan',
    Tajikistan: 'Tayikistan',
    Tanzania: 'Tanzania',
    Thailand: 'Tailandia',
    Timor: 'Timor-Leste',
    Togo: 'Togo',
    Tokelau: 'Tokelau',
    Tonga: 'Tonga',
    Trinidad: 'Trinidad y Tobago',
    Tunisia: 'Tunez',
    Turkey: 'Pavo',
    Turkmenistan: 'Turkmenistan',
    Turks: 'Islas Turcas y Caicos',
    Tuvalu: 'Tuvalu',
    Uganda: 'Uganda',
    Ukraine: 'Ucrania',
    United: 'Emiratos arabes Unidos',
    United: 'Reino Unido',
    United: 'Estados Unidos',
    Uruguay: 'Uruguay',
    Uzbekistan: 'Uzbekistan',
    Vanuatu: 'Vanuatu',
    Vatican: 'Ciudad del Vaticano',
    Venezuela: 'Venezuela',
    Vietnam: 'Vietnam',
    Virgin: 'Islas Virgenes-British',
    Virgin: 'Islas Virgenes-US',
    Wallis: 'Wallis y Futuna',
    Yemen: 'Yemen',
    Zambia: 'Zambia',
    Zimbabwe: 'Zimbabue',
    America: 'America',
    Burma: 'Birmania',
    DRC: 'DRC',
    East: 'Timor este',
    England: 'Inglaterra',
    Holland: 'Holanda',
    Holy: 'Ciudad santa',
    Persia: 'Persia',
    Sint: 'Sint Maarten',
}

export {countries, countries_api2};